// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGPoERlUHdR4VFOPQimxYJoPuZeD6U_lc',
    appId: '1:929826301570:web:e41a109b2992c3d9d1f69b',
    messagingSenderId: '929826301570',
    projectId: 'sendit-9c20f',
    authDomain: 'sendit-9c20f.firebaseapp.com',
    storageBucket: 'sendit-9c20f.firebasestorage.app',
    measurementId: 'G-N9NR312L8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCACSKjhgvR_QN8I7GY6_iOw7-YKiCjEyc',
    appId: '1:929826301570:android:628972a47a68d95cd1f69b',
    messagingSenderId: '929826301570',
    projectId: 'sendit-9c20f',
    storageBucket: 'sendit-9c20f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgnJk-ygw2XKiPicQcSu4AwLTkP9BpbyU',
    appId: '1:929826301570:ios:e9554be30f0b1da2d1f69b',
    messagingSenderId: '929826301570',
    projectId: 'sendit-9c20f',
    storageBucket: 'sendit-9c20f.firebasestorage.app',
    iosBundleId: 'com.example.senditadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgnJk-ygw2XKiPicQcSu4AwLTkP9BpbyU',
    appId: '1:929826301570:ios:e9554be30f0b1da2d1f69b',
    messagingSenderId: '929826301570',
    projectId: 'sendit-9c20f',
    storageBucket: 'sendit-9c20f.firebasestorage.app',
    iosBundleId: 'com.example.senditadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGPoERlUHdR4VFOPQimxYJoPuZeD6U_lc',
    appId: '1:929826301570:web:4dbe3c6ce4500081d1f69b',
    messagingSenderId: '929826301570',
    projectId: 'sendit-9c20f',
    authDomain: 'sendit-9c20f.firebaseapp.com',
    storageBucket: 'sendit-9c20f.firebasestorage.app',
    measurementId: 'G-77QRPHWMHY',
  );
}
